import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import DiscordSDKProvider from '@/lib/DiscordSDKProvider';
import { SidebarProvider } from '@/components/ui/sidebar';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { SharedStateProvider } from '@/lib/SharedStateProvider';
config.autoAddCss = false;

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <DiscordSDKProvider>
          <SharedStateProvider>
            <SidebarProvider>{children}</SidebarProvider>
          </SharedStateProvider>
        </DiscordSDKProvider>
      </body>
    </html>
  );
}
